openapi: 3.0.1
info:
  title: Library API
  version: 1.0.0
paths:
  /author:
    $ref: '../components/book.yaml#/schemas/BookRequest'
  /author/{id}:
    get:
      tags:
        - Author
      operationId: get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Retrieved by id
          content:
            application/json:
              schema:
                $ref: '../models/author.yaml#/components/schemas/Author'
  /author/{id}/books:
    get:
      tags:
        - Author
      operationId: searchBooks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: filter
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of books
          content:
            application/json:
              schema:
                $ref: '../models/book.yaml#/components/schemas/BooksList'
  /book:
    post:
      tags:
        - Book
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../models/book.yaml#/components/schemas/BookRequest'
      responses:
        200:
          description: Model was created
          content:
            application/json:
              schema:
                $ref: '../models/book.yaml#/components/schemas/Book'
